apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  generation: 1
  labels:
    application: helloworld
  name: helloworld
spec:
  rules:
  - host: helloworld.host
    http:
      paths:
      - backend:
          serviceName: helloworld
          servicePort: 80
        path: /
